name: bird-pearls-of-functional-algorithm-design

dependencies:
    - base
    - array

library:
    source-dirs: src

tests:
    all-tests:
        main: Spec.hs
        source-dirs: test
        dependencies:
            - QuickCheck
            - bird-pearls-of-functional-algorithm-design
